function reset_progress(){
//Character Stats
store.player_max_hp = 30
store.player_regen = 0
store.player_defense = 0
store.player_speed = 2.3
store.player_attack_damage=0
store.player_critical_chance=0
store.player_critical_multiplier=2
store.player_luck=0
store.player_xp_gain=1
store.player_attraction=0
//Upgrades
store.cost_maxhealth=5
store.cost_regen=25
store.cost_defense=5
store.cost_speed=10
store.cost_damage=5
store.cost_crit_chance=5
store.cost_crit_multiplier=5
store.cost_luck=10
store.cost_xp_gain=50
store.cost_attaction=25
//cards 
store.slot_2_unlocked = 0
store.slot_3_unlocked = 0
store.slot_4_unlocked = 0
store.card_cost = 10
store.card_slot_1 = 0
store.card_slot_2 = 0
store.card_slot_3 = 0
store.card_slot_4 = 0
store.card_metal = 0
store.card_lvl_metal = 1
store.card_pinata = 0
store.card_lvl_pinata = 1
store.card_fetch = 0
store.card_lvl_fetch = 1
store.card_pizza = 0
store.card_lvl_pizza = 1
store.card_repulse = 0
store.card_lvl_repulse = 1
store.card_critgold = 0
store.card_lvl_critgold = 1
store.card_mastery=0
store.card_lvl_mastery=1
store.card_necro=0
store.card_lvl_necro=1
store.card_revive=0
store.card_lvl_revive=1
store.card_vampire=0
store.card_lvl_vampire=1
//Misc
store.current_stage = 1
store.bonus_discord=0
store.gold = 0
store.character=1
store.character_unlocked = 1
store.polygun_unlocked=0
store.slogun_unlocked=0
store.scale_creep=0
//Challenges
store.challenge_a=0
store.challenge_b=2
store.challenge_c=4
store.challenge_wisdom=0
store.challenge_adapt=0
store.challenge_slayer=0
store.challenge_homeslice=0
store.challenge_hero=0
store.challenge_bigbang=0
store.challenge_eagleeyes=0
//Statistics
store.enemies_killed=0
store.gold_earned=0
store.level_gained=0
store.games_played=0
store.challenges_completed=0
store.neighbors_saved=0
store.suburbs_best_minute=0
store.suburbs_best_second=0
store.suburbs_best_level=0
store.lab_best_minute=0
store.lab_best_second=0
store.lab_best_level=0
store.lab_best_saved=0
store.cemetary_best_minute=0
store.cemetary_best_second=0
store.cemetary_best_level=0
store.mall_best_minute=0
store.mall_best_second=0
store.mall_best_level=0
store.mall_best_saved=0
store.airport_best_minute=0
store.airport_best_second=0
store.airport_best_level=0
store.airport_best_saved=0
//Settings
store.draw_shadows = 1
store.show_minihealthbar = 1
store.show_fps = 0
store.audio=1
store.gameSpeed = 1
store.show_all_healthbars=0
store.joystick_mode=0
//Bonus Codes
store.code_payday=0
store.code_cashcow=0
store.code_survive=0
store.code_sparechange=0
store.code_jackpot=0
store.code_genetix=0
store.code_cookie=0
store.code_zombie=0
store.code_blood=0
store.code_bonfire=0
}